s2e_env/templates/s2e-config.linux.lua
=> s2e-config: removed duplicate TranslationBlockCoverage

s2e_env/command.py
Fixed bug when logger was called before it was initialized
=> Logger bugfixes

s2e_env/commands/code_coverage/basic_block.py, s2e_env/commands/code_coverage/lcov.py, s2e_env/commands/new_project.py, s2e_env/templates/s2e-config.lua
Just some minor things.
* Improved the basic block output to display some stats
* After analysing some malware, I realised that the Windows regexes were incorrect. So I fixed them
This should be an easy one! :)
=> Improvements and fixes

README.md, s2e_env/commands/coverage.py, s2e_env/commands/run.py
* Added some documentation on running commands from Python code
* Added a timeout option to the `s2e run` command
=> Run improvements

s2e_env/commands/project_creation/__init__.py
=> new_project: fixed image download

s2e_env/commands/project_creation/__init__.py, s2e_env/commands/project_creation/config.py, s2e_env/server/__init__.py
* More refactoring
* Fixed a typo (not sure why I didn't notice with pylint! ☹️)
* Refactored validation routines. The exception was always swallowed up and ignored, so throwing it in the first place was largely pointless. It also made debugging difficult (because who knows what exception is being thrown? Because of a typo? Because the validation failed?). Instead the validation routines return True or False depending on if they succeed
=> New project fixes

s2e_env/commands/code_coverage/lcov.py
I used a simple program to test "s2e coverage lcov", and it didn't generate any coverage report. I found the original script skip any compilation unit without "include_directory" property. So I removed that branch, I'm not sure if it's the correct way to do that. Please check with it. Thanks!
=> coverage: fixed unable to process null include_directory file

s2e_env/commands/build.py
Fixes a common question on how to rebuild S2E.
Requires https://github.com/S2E/build-scripts/pull/12
=> build: rebuild specific components

README.md, s2e_env/commands/init.py, s2e_env/commands/new_project.py, s2e_env/commands/project_creation/__init__.py, s2e_env/templates/bootstrap.linux.sh, s2e_env/templates/bootstrap.sh
=> new_project: make symbolic arguments more intuitive

s2e_env/commands/build.py, s2e_env/templates/bootstrap.cgc.sh, s2e_env/templates/bootstrap.linux.sh, s2e_env/templates/bootstrap.windows.sh, s2e_env/templates/bootstrap.windows_common.sh, s2e_env/templates/bootstrap.windows_dll.sh
Goes with https://github.com/S2E/s2e-linux-kernel/pull/4
=> bootstrap: start the LinuxMonitor driver

s2e_env/commands/execution_trace.py
The test case data must be hexlified otherwise` json.dump` may fail because it cannot properly encode UTF-8.
=> execution_trace: hexlify the test case data

README.md, s2e_env/commands/code_coverage/binaryninja_basic_block.py, s2e_env/commands/code_coverage/ida_basic_block.py, s2e_env/commands/code_coverage/r2_basic_block.py, s2e_env/commands/coverage.py, s2e_env/templates/s2e.yaml
Last disassembler backend, I swear!! I just really like [Binary Ninja](https://binary.ninja), and I don't really have access to IDA anymore.
=> Added Binary Ninja disassembler backend

s2e_env/commands/export_project.py
When you tried to export a project containing either a seeds or recipes directory, s2e-env would crash because it would read the path to the seeds/recipes directory from the exported project.json file.
Unfortunately, the exported project.json file has already had its paths overwritten with the `S2E_ENV_PLACEHOLDER` token (used by the `import_project` command), so when s2e-env tried to access the seeds/recipes directory, it would do so via an invalid path.
To fix this we maintain a file handle to the original project.json file and read the seeds/recipes directory path from there.
=> export_project: bugfix when exporting seeds/recipes

s2e_env/dat/config.yaml
https://github.com/S2E/s2e-env/issues/73
=> config: added jigdo-file package

s2e_env/execution_trace/trace_entries.py
Now includes the process return code. Goes with https://github.com/S2E/libs2eplugins/pull/18
=> execution_trace: updated TraceProcessUnload struct

s2e_env/commands/image_build.py
This allows images to be built on WSL, etc. Addresses https://github.com/S2E/s2e-env/issues/68
=> image_build: added option to disable KVM

s2e_env/templates/bootstrap.windows_common.sh, s2e_env/templates/bootstrap.windows_driver.sh
=> templates: updated driver testing template

s2e_env/commands/new_project.py
=> new_project: small fixes for targetless config

s2e_env/execution_trace/trace_entries.py
=> trace_entries: improved test case format

s2e_env/dat/config.yaml
=> dat: added multilib packages

s2e_env/commands/build.py, s2e_env/commands/code_coverage/__init__.py, s2e_env/commands/code_coverage/basic_block.py, s2e_env/commands/code_coverage/lcov.py, s2e_env/commands/coverage.py, s2e_env/commands/execution_trace.py, s2e_env/commands/forkprofile.py, s2e_env/commands/image_build.py, s2e_env/commands/init.py, s2e_env/commands/new_project.py, s2e_env/commands/project_creation/__init__.py, s2e_env/commands/recipe.py, s2e_env/dat/config.yaml, s2e_env/execution_trace/analyzer.py, s2e_env/execution_trace/trace_entries.py, s2e_env/infparser/case_insensitive_dict.py, s2e_env/infparser/driver.py, s2e_env/infparser/file.py, s2e_env/manage.py, s2e_env/server/__init__.py, s2e_env/server/coverage.py, s2e_env/server/queueprocessor.py, s2e_env/symbols/__init__.py, s2e_env/templates/bootstrap.sh, s2e_env/utils/google.py, s2e_env/utils/images.py
=> Added support for Ubuntu 18 04

s2e_env/commands/new_project.py
Simple change. I need to programatically create S2E projects and so need to pass args. No change to functionality.
=> new_project: pass args

tests/analysis/test_elf.py
Now that we have some testing infrastructure in place, I'd like to start fleshing out all the different s2e-env components to make them testable.
I've started with a simple test of the ELF static analysis. This one is standalone because I'm not sure when I'll get the chance to write all the different tests (probably not for a couple weeks).
=> tests: added analysis tests

README.md, setup.py
=> setup.py: fixed dependency links for pip 19

s2e_env/__init__.py, s2e_env/command.py, s2e_env/commands/new_project.py, s2e_env/commands/testsuite.py
=> new_project: removed reference to concolic file

s2e_env/dat/config.yaml
=> config: added missing dependencies

README.md, s2e_env/dat/config.yaml
=> Phased out Ubuntu 16 support

s2e_env/commands/testsuite.py
=> testsuite: pass additional params to the post gen script

s2e_env/commands/update.py
=> commands/updated: fixed typo

s2e_env/templates/launch-s2e.sh
=> templates/launch-s2e: fixed path for new repo org

s2e_env/commands/build.py
Fixes https://github.com/S2E/s2e-env/issues/457
=> commands/build: fixed rebuilding of individual components

s2e_env/commands/init.py, s2e_env/templates/launch-s2e.sh, s2e_env/templates/s2e-config.lua
This goes together with https://github.com/S2E/s2e/pull/63
=> Enable StatsTracker plugin

s2e_env/templates/plugin_creation/plugin.h.template
I used `s2e new_plugin` to create my custom plugin from the template. Simple bugs were found in the template.
=> Quick fix of plugin template

s2e_env/commands/new_project.py, s2e_env/commands/project_creation/base_project.py, s2e_env/commands/project_creation/cgc_project.py, s2e_env/commands/recipe.py, s2e_env/server/web_service_interface.py, s2e_env/templates/bootstrap.cgc.sh, s2e_env/templates/s2e-config.cgc.lua, s2e_env/templates/verify-pov.sh, s2e_env/tui/tui.py
https://github.com/S2E/s2e-env/issues/503
=> Updated CGC binary support
