s2e_env/dat/config.yaml
Added 'p7zip-full' as a dependency to install /usr/bin/7z as 'p7zip' only installs /usr/bin/7zr and /usr/bin/p7zip. (Ubuntu 16.04 LTS Server x86-64)
=> p7zip-full dependency

s2e_env/commands/code_coverage/lcov.py
If the user does not have this package installed, then they can still generate the lcov file (just not the html report).
=> lcov: lazily load the genhtml command

s2e_env/commands/code_coverage/__init__.py, s2e_env/commands/code_coverage/basic_block.py
Occasionally IDA will fail to generate any basic blocks (e.g. due to heavy obfuscation), leading to a divide-by-zero in the statistics calculation. I've added some checks to avoid this.
=> basic_block_coverage: improvements

s2e_env/commands/init.py
If something goes wrong during environment initialisation, clean up the half-complete env. It can be confusing for new users if they have an environment but they are unsure if it is actually valid or not. So better to start from scratch.
=> init: clean up S2E Environment directory on failure

s2e_env/templates/bootstrap.cgc.sh, s2e_env/templates/bootstrap.linux.sh, s2e_env/templates/bootstrap.windows.sh
Do not render the `execute_target_with_seed` function if seeds are not in use - makes the bootstrap.sh file simpler and easier to understand
=> bootstrap.sh: hide unused functions

README.md, s2e_env/commands/init.py, s2e_env/dat/config.yaml
Enable 32-bit libraries and makes clearer what versions of Ubuntu we support.
Fixes issues #33, #34 and #36.
=> s2e init error fix

README.md, s2e_env/commands/export_project.py, s2e_env/commands/import_export/__init__.py, s2e_env/commands/import_project.py, s2e_env/commands/project_creation/__init__.py, s2e_env/dat/config.yaml, s2e_env/manage.py, s2e_env/templates/bootstrap.windows.sh, s2e_env/templates/bootstrap.windows_dll.sh, s2e_env/templates/launch-s2e.sh, s2e_env/templates/s2e-config.lua
Just something I did for "fun" over the weekend.
Allows the user to export projects to share with others (e.g. to upload to the s2e-dev google group, share with other S2E users, etc.). When exporting a project, all references to the S2E environment path are replaced with a placeholder that gets rewritten with the new S2E environment path when imported.
I wanted to add a `--contact-vitaly` option to the `s2e export_project` command for when people need help, but maybe that wait for a future PR 🙂
=> Added import and export commands

s2e_env/templates/instructions.txt
The instructions template was expecting a `modelled_funcs` context variable. However the Python code actually uses `modelled_functions`.
=> instructions: function models insts not rendered

README.md, s2e_env/commands/execution_trace.py, s2e_env/execution_trace/__init__.py, s2e_env/execution_trace/trace_entries.py, setup.py
New command to parse an Execution trace into human-readable JSON. Works for both single and multi process traces.
Allows the user to specify specific paths to include in the trace - all other paths are filtered out.
=> Added ExecutionTracer.dat parser

s2e_env/dat/config.yaml
Tried running `s2e init` on my Ubuntu 16.10. The apt requirement didn't exist as stated. Would think that allowing it to be generic would work across the different 16s.
=> Different apt dep for Ubuntu 16.10

s2e_env/analysis/elf.py, s2e_env/dat/config.yaml
An ELF file can have multiple symbol tables. If this is the case, then the `modelled_functions` list could be blatted out by multiple symbol tables.
I've changed the way we construct this list to prevent this from happening.
=> elf: fixed function models check

s2e_env/templates/models.lua
I've had a few people make this mistake (yes, including me!) - replace
```lua
g_function_models["{{ target }}"] = {}
```
with
```lua
g_function_models["{{ target }}"][0x1234] = {
xor_result=true, --Must be true for standard CRC32
type="crc32"
}
```
And then the models don't work because the table at `g_function_models["{{ target }}"]` doesn't exist.
Hopefully this makes it clearer that the empty table should not be replaced!
=> models.lua: made static function models config clearer

s2e_env/templates/s2e-config.linux.lua
`terminateOnSegfault` not `terminateOnSegFault`.
=> s2e-config.linux.lua: incorrect LinuxMonitor option

s2e_env/templates/instructions.txt, s2e_env/templates/s2e-config.lua
Preference running launch-s2e.sh over the "s2e run" command (because "s2e run" is not very useful for non-CGC binaries).
=> templates: minor fixes

README.md, s2e_env/command.py, s2e_env/commands/init.py, s2e_env/templates/s2e_activate.sh
Adds an environment activation script (currently only BASH is supported), similar to a Python virtualenv. This allows the user to run `s2e` commands from any location (previously the user had to be in the environment's root directory) and have the command run in the currently-activated environment.
=> Make s2e-env more "virtualenv"-ish

s2e_env/command.py
I accidentally removed this. If you are using an existing S2E environment (i.e. one that doesn't have the s2e_activate.sh script), then you'll probably get funny behaviour. Sorry! 😞
=> command: returned default env directory to cwd

s2e_env/commands/new_project.py, s2e_env/commands/project_creation/config.py
This is inline with the WindowsMonitor plugin.
Also moved the Windows configuration to a common base-class (lots of duplicate checks for 'pe' in `os_desc`).
=> project config: convert Windows module names to lower-case

s2e_env/templates/bootstrap.cgc.sh, s2e_env/templates/bootstrap.linux.sh, s2e_env/templates/bootstrap.sh, s2e_env/templates/bootstrap.windows_common.sh
Super small cleanup!!
Previously Windows VMs would download the Linux common tools (e.g. s2eget, etc.), which aren't usable on a Windows system.
=> bootstrap template: VM only downloads required tools

s2e_env/commands/new_project.py, s2e_env/commands/project_creation/__init__.py, s2e_env/templates/bootstrap.sh
This is useful when there isn't really a target to analyze, or the desired target is not supported by s2e-env. This gives the option of configuring everything manually. The command still provides a default project skeleton for the type of OS requested.
=> Empty project

s2e_env/templates/s2e-config.linux.lua
Since use_test_case_generator is true in Linux, TestCaseGenerator will be included in s2e-config.lua for Linux. However, since there is another TestCaseGenerator option in s2e-config.linux.lua, it results in duplication.
=> Remove TestCaseGenerator from Linux template

setup.py
The upstream one is not compatible with the latest sorted containers
=> Use our own fixed version of pytrie

s2e_env/commands/new_project.py
Otherwise the symlinks in the project directory will not work correctly.
=> new_project: convert target to absolute path

s2e_env/dat/config.yaml, s2e_env/templates/launch-s2e.sh
=> templates: fixed gdb.ini creation + block SIGUSR1

s2e_env/commands/image_build.py
Pointed out by a user when they tried to use a relative path to specify the ISO dir. Results in a nonsense error by `make` when the current working directory is changed.
=> image_build: ensure ISO dir path is absolute

s2e_env/commands/run.py
Hi,
This patch allows early termination when execution time is less than timeout.
This patch is extremely useful and can save time when doing batch run.
Please consider pulling if you think this is useful.
Thanks.
- Tong
=> allow early termination when timeout is set

s2e_env/templates/s2e-config.lua
The LuaCoreEvents example is not commented out properly, which will suppress the onStateForkDecide functions in other plugins.
Signed-off-by: Zhongjie Wang <wzj401@gmail.com>
=> templates/s2e-config.lua: fixed incorrect commenting for the LuaCoreEvents example

s2e_env/commands/new_plugin.py, setup.py
This PR removes the pygit2 dependency, which was previously used to get the plugin author's full name in the `new_plugin` command. Now, the command gets the username from either the optional `--author-name` command line argument or, as a fallback, through `getpass.getuser()`.
fixes #455
=> Remove pygit2 dependency

s2e_env/utils/google.py
This PR fixes the `s2e build-image` function, which was recently broken by an API change.
Closes #458
=> Update GDrive download code to new API

README.md
After I ran step 1 of workflow, I found the file "s2e_activate" was located at $DIR, not $DIR/install/bin.
=> README: update the workflow

s2e_env/commands/new_project.py, s2e_env/commands/project_creation/__init__.py, s2e_env/commands/project_creation/abstract_project.py, s2e_env/commands/project_creation/base_project.py, s2e_env/commands/project_creation/bios_project.py, s2e_env/templates/launch-s2e.sh, s2e_env/templates/s2e-config.bios.lua, test.sh
s2e new_project can now create a project for BIOSes (using -bios QEMU command line argument).
This is mostly used to configure a project to run the S2E BIOS to test the engine. No plugin/tooling is available in S2E yet.
=> Added BIOS project support
